### PR TITLE
2016 cgbg

### PR DESCRIPTION
**Pull request by halindrome**
Added logos and stylesheets for community group and business group reports.

I am adding support for using these to ReSpec as well.

### CODE REVIEW

**Comment by plehegar** [comment]
this looks good to me.

**Comment by halindrome** [comment]
I will leave it in your capable hands to merge / deploy in conjunction with the launch tomorrow.  I will update respec and reference this PR.

**Comment by iherman** [comment]
Just for the records: a version of the updated epub generation is running on my machine but I want to test it with the new respec before deploying it.

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by marcoscaceres** [comment]
Will merge soon

**Comment by marcoscaceres** [comment]
Oops, wrong repo... Shouldn't be doing git tasks on my phone :)

**Pull request merged**
