### PR TITLE
Add analytics to TR specs

### PR DESCRIPTION
**Pull request by deniak**
In the past, we received requests to add analytics to our specs. Since the request resurfaced recently, that PR adds a script to enable it on all our TR specifications.

### CODE REVIEW

**Comment by vivienlacourba** [comment]
Hi @deniak ,

Per our discussion some questions for you:

- Can we use the same site as the main W3C website instead of creating a separate site for /TR? (you might want to consult with @jean-gui )
- What happens when this js is loaded from a page which is not served by www.w3.org? (e.g. page is loaded locally or served by github.io or other non w3.org servers)
- If we only care about requests from www.w3.org should this code be modified only ping Matomo when the page uri starts with www.w3.org (this would avoid unneeded network access and requests to the analytics backend server)
- Is fixup.js loaded for editors drafts or community drafts docs? If it is do we care about stats on editors drafts that are not served from www.w3.org? (I think we don't)
- Do we care about stats on cg reports/drafts? (I would say yes)
- Analytics should also be enabled on older specs
- _(Code cleanup - low priority)_ It does not seem very clean to have all those different features (toc fixup, outdated warning, and analytics) defined in the same js file and with part of it duplicated in other files.

**Review by vivienlacourba — CHANGES_REQUESTED** [review]
Hi @deniak ,

Per our discussion some questions for you:

- Can we use the same site as the main W3C website instead of creating a separate site for /TR? (you might want to consult with @jean-gui )
- What happens when this js is loaded from a page which is not served by www.w3.org? (e.g. page is loaded locally or served by github.io or other non w3.org servers)
- If we only care about requests from www.w3.org should this code be modified to only ping Matomo when the page uri starts with www.w3.org (this would avoid unneeded network access and requests to the analytics backend server)
- Is fixup.js loaded for editors drafts or community drafts docs? If it is do we care about stats for editors drafts that are not served from www.w3.org? (I think we don't)
- Do we care about stats on CG reports/drafts? (I would say yes)
- Analytics should also be enabled on older specs
- _(Code cleanup - low priority)_ It does not seem very clean to have all those different features (toc fixup, outdated warning, and analytics) defined in the same js file and with part of it duplicated in other files.

**Comment by vivienlacourba** [comment]
> Do we care about stats on CG reports/drafts? (I would say yes)

Thinking about it the CG reports are very often not served from www.w3.org.
So it might be simpler if we only handle stats for TR documents ie when URIs stats with www.w3.org/TR/...

**Comment by deniak** [comment]
>     * Can we use the same site as the main W3C website instead of creating a separate site for /TR? (you might want to consult with @jean-gui )

I updated the tracking code to re-use the one from the main website. The less matomo sites we have the better.

> 
>     * What happens when this js is loaded from a page which is not served by [www.w3.org](http://www.w3.org)? (e.g. page is loaded locally or served by github.io or other non w3.org servers)
> 
>     * If we only care about requests from [www.w3.org](http://www.w3.org) should this code be modified to only ping Matomo when the page uri starts with [www.w3.org](http://www.w3.org) (this would avoid unneeded network access and requests to the analytics backend server)

https://github.com/w3c/tr-design/pull/229/commits/1ac621ac8e5cb6dfa11196ce8c98e7f81553c58c will filter the requests and track only the requests for specs on https://www.w3.org/TR/.

> 
>     * Is fixup.js loaded for editors drafts or community drafts docs? If it is do we care about stats for editors drafts that are not served from [www.w3.org](http://www.w3.org)? (I think we don't)

For ED, they probably all have it as it's needed for the TOC and one of pubrules requirements.
Regarding CG specs, I'd say it depends if they were generated with a spec generator.
In both case, the filter described above should skip these requests.

> 
>     * Do we care about stats on CG reports/drafts? (I would say yes)

It would be an interesting data to have indeed.

> 
>     * Analytics should also be enabled on older specs

This will be the case. We have a alternate version of fixup.js for old specs so I'll report the tracking code there once the PR is merged.

> 
>     * _(Code cleanup - low priority)_ It does not seem very clean to have all those different features (toc fixup, outdated warning, and analytics) defined in the same js file and with part of it duplicated in other files.

Indeed, fixup.js is becoming bigger and has different purposes. In the future, we may want to separe it into different scripts and repckage it before deployment.

**Review by vivienlacourba — APPROVED** [review]

**Comment by deniak** [comment]
I created a [separe issue](https://github.com/w3c/tr-design/issues/230) regarding the fixup.js enhancements

**Pull request merged**
