### PR TITLE
drop speech block, which is completely unused anywhere

### PR DESCRIPTION
**Pull request by darobin**

### CODE REVIEW

**Comment by astorije** [comment]
Isn't that useful for screen readers? Or any other accessibility-related purposes?

**Comment by darobin** [comment]
Nope, it's not implemented!

**Comment by plehegar** [comment]
Note that it'll refrain from merging stuff until I found a point person to manage the pull requests but this is definitively a good candidate for merge.

**Comment by fantasai** [comment]
There are implementations, or at least one (emacs), which are in use by some members of the blind community. However, I suspect this bock is doing more harm than good.

**Pull request merged**
