### PR TITLE
Add png version of the logos

### PR DESCRIPTION
**Pull request by deniak**
generated with inkscape with:
`inkscape --export-type="png"  @@.svg`

### CODE REVIEW

**Comment by fantasai** [comment]
@deniak I can't see the images, I think? So can't really review them. :) But looking at what was generated for CRD earlier: 
  https://www.w3.org/StyleSheets/TR/2016/logos/CRD

It's not using the right fonts, and is clipped besides! Compare to the CR logo:
  https://www.w3.org/StyleSheets/TR/2016/logos/CR

So, you have to make sure you get this right. You might need to increase the size of some of the images so that all the text fits, and you need to make sure you have the right fonts.

**Comment by fantasai** [comment]
Oh also, you should just push the path edits to fixup.js to the main branch. That commit doesn't really belong here...

**Comment by deniak** [comment]
> @deniak I can't see the images, I think? So can't really review them. :) But looking at what was generated for CRD earlier: https://www.w3.org/StyleSheets/TR/2016/logos/CRD
> 
> It's not using the right fonts, and is clipped besides! Compare to the CR logo: https://www.w3.org/StyleSheets/TR/2016/logos/CR
> 
> So, you have to make sure you get this right. You might need to increase the size of some of the images so that all the text fits, and you need to make sure you have the right fonts.

@fantasai, yeah, we discussed the logos with @plehegar and we had a hard time finding how the previous logos were generated. Do you remember what font and size were used?
The current svg are edited manually but there may be better options to generate all the logos.

**Comment by deniak** [comment]
> Oh also, you should just push the path edits to fixup.js to the main branch. That commit doesn't really belong here...

Indeed, I created a separate PR: https://github.com/w3c/tr-design/pull/256

**Comment by deniak** [comment]
The png logos on that branch can been seen on statically:
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/CR.png
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/CRD.png
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/CRY.png
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/CRYD.png
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/DNOTE.png
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/DRY.png
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/ED.png
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/NOTE.png
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/PR.png
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/REC.png
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/RY.png
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/STMT.png
https://cdn.statically.io/gh/w3c/tr-design/logo-png/p2021mockup/style/logos/WD.png

**Review by plehegar — APPROVED** [review]

**Comment by fantasai** [comment]
@deniak Those are all 404. As for the fonts and stuff, ask @bert-github he might remember.

**Comment by deniak** [comment]
@fantasai, the links no longer exists because the PR was merged yesterday.
To prepare the release of the new process, I've deployed the png (see links below). @bert-github, feel free to update the logo if there's a problem or let me know how I can generate those.

- https://www.w3.org/StyleSheets/TR/2021/logos/CR.png
- https://www.w3.org/StyleSheets/TR/2021/logos/CRD.png
- https://www.w3.org/StyleSheets/TR/2021/logos/CRY.png
- https://www.w3.org/StyleSheets/TR/2021/logos/CRYD.png
- https://www.w3.org/StyleSheets/TR/2021/logos/DNOTE.png
- https://www.w3.org/StyleSheets/TR/2021/logos/DRY.png
- https://www.w3.org/StyleSheets/TR/2021/logos/ED.png
- https://www.w3.org/StyleSheets/TR/2021/logos/NOTE.png
- https://www.w3.org/StyleSheets/TR/2021/logos/PR.png
- https://www.w3.org/StyleSheets/TR/2021/logos/REC.png
- https://www.w3.org/StyleSheets/TR/2021/logos/RY.png
- https://www.w3.org/StyleSheets/TR/2021/logos/STMT.png
- https://www.w3.org/StyleSheets/TR/2021/logos/WD.png

**Comment by plehegar** [comment]
I checked a PNG and it seems to use the right font. @fantasai , I suspect you looked at the SVG without having the proper font installed, thus the clipped text.

**Comment by bert-github** [comment]
I see that Denis converted the text in the SVG files to paths, after the previous comment. So they no longer depend on installed fonts.

Re how they were generated: As far as I know, these logos were never generated, but always made by hand. There is also no recipe for the color and font, each logo was just made by modifying another. The first ones were in GIF and PNG and were made before 2000, probably in 1999, I think by Ian. The first ones didn't use Gill Sans either, but Verdana. Susan Lesch changed the font in 2003. And Ian recreated them all in 2006 by making SVG versions for all of them and exporting PNG and GIF from those.

But if we continue inventing new document statuses, a recipe might be useful. Here is one:
```
<svg xmlns="http://www.w3.org/2000/svg"
width="25" height="380" viewBox="0 0 25 380">
<rect x="0" y="0" width="250" height="380" fill="#1a5e9a"/>
<text x="-30" y="18" transform="rotate(-90)" fill="#fff" font-size="20"
font-family="Gill Sans,Lato" text-anchor="end">W3C Lorem Ipsum</text>
</svg>
```
Replace the ‘Lorem Ipsum’, make sure you have Gill Sans installed, then convert the text to a path with
```
inkscape -l -T this-template.svg -o newfile.svg
```
And if you can't get Gill Sans but still need to generate a logo, install Lato instead. It's not the same, but reasonably similar.

Back to the subject of this pull request: The 2021 style sheets link directly to the SVG versions. They do not do content negotiation. Why are the PNG versions needed?

**Pull request merged**
