### PR TITLE
LC style somehow contained base.css verbatim instead of through an include

### PR DESCRIPTION
**Pull request by darobin**

### CODE REVIEW

**Comment by astorije** [comment]
:+1:

**Comment by astorije** [comment]
Merging myself as @plehegar will be away for a few days.

**Comment by tripu** [comment]
(So @plehegar found [&ldquo;a point person to manage the pull requests&rdquo;](https://github.com/w3c/tr-design/pull/8#issuecomment-91625645), then&hellip; :¬)

**Comment by plehegar** [comment]
at least, that one was just an oversight :)

**Pull request merged**
