### PR TITLE
Added CSS Validation and printing as considerations

### PR DESCRIPTION
**Pull request by plehegar**
Additional aspects to consider when designing new TR styles

### CODE REVIEW

**Comment by halindrome** [comment]
Thank you!

I imagine smart people could devise a test suite to help evaluate the various requirements on any design changes.

**Comment by tripu** [comment]
LGTM.

**Comment by fantasai** [comment]
Hmm, I definite agree with the printing considerations. Wrt CSS validation... The CSS should be valid. But the validator is often behind on what is valid, and imho shouldn't be a blocker here.

**Comment by fantasai** [comment]
Switched to "Use valid CSS and follow CSS best practices."

**Pull request merged**
